sonar.projectKey=Sar-py-05_hprofile
sonar.organization=sar-py-05

sonar.sources=src
sonar.java.binaries=target/classes

sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
