name: Hprofile Action

on:
  workflow_dispatch:

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"
          cache: maven

      - name: Maven Test
        run: mvn test

      - name: Verify Sonar Secrets
        run: |
          echo "ORG=${{ secrets.SONAR_ORGANIZATION }}"
          echo "PROJECT=${{ secrets.SONAR_PROJECT_KEY }}"
          echo "URL=${{ secrets.SONAR_URL }}"

          if [ -n "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "SONAR_TOKEN_PRESENT=YES"
          else
            echo "SONAR_TOKEN_PRESENT=NO"
            exit 1
          fi

      - name: Setup Sonar Scanner
        uses: warchant/setup-sonar-scanner@v7

      - name: Sonar Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=${{ secrets.SONAR_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
